---
- name: Deploy Web App
  hosts: node-2
  become: yes

  tasks:
  - name: Install Git
    yum:
      name: git
      state: present   

  - name: Host code
    git:
      repo: https://github.com/nottie-noe/ansible-work-1.git
      dest: /www/var/html  

  - name: Enable httpd
    service:
      name: httpd
      enabled: yes 

...           