---
- name: Install HTTP server
  hosts: g1
  become: yes

  tasks:
  - name: Install HTTPD (Amazon Linux)
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "Amazon"

  - name: Start HTTPD
    service:
      name: httpd
      state: started  
    when: ansible_distribution == "Amazon"

  - name: Enable HTTPD
    service:
      name: httpd
      enabled: yes 
    when: ansible_distribution == "Amazon"

  - name: Update package cache (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  
  - name: Install Apache2 (Ubuntu)
    apt:
      name: apache2
      state: present   
    when: ansible_distribution == "Ubuntu"

  - name: Start Apache2
    service:
      name: apache2
      state: started  
    when: ansible_distribution == "Ubuntu"

  - name: Enable Apache2
    service:
      name: apache2
      enabled: yes 
    when: ansible_distribution == "Ubuntu"
