---
- name: Install HTTP server on Debian and CentOS 10
  hosts: g3
  become: yes

  tasks:
  
  # CentOS 10 Installation
  - name: Install HTTPD (CentOS 10)
    dnf:
      name: httpd
      state: present
    when: ansible_distribution == "Amazon" or ansible_distribution == "CentOS"

  - name: Start HTTPD (CentOS 10)
    service:
      name: httpd
      state: started  
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

  - name: Enable HTTPD (CentOS 10)
    service:
      name: httpd
      enabled: yes 
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

  # Debian Installation
  - name: Update package cache (Debian)
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian" or ansible_distribution == "Amazon"
  
  - name: Install Apache2 (Debian)
    apt:
      name: apache2
      state: present   
    when: ansible_distribution == "Debian" or ansible_distribution == "Amazon"

  - name: Start Apache2 (Debian)
    service:
      name: apache2
      state: started  
    when: ansible_distribution == "Debian" or ansible_distribution == "Amazon"

  - name: Enable Apache2 (Debian)
    service:
      name: apache2
      enabled: yes 
    when: ansible_distribution == "Debian" or ansible_distribution == "Amazon"
