---
- name: Deploy the static page with system information
  hosts: g1
  become: yes

  tasks:
    - name: Ensure target directory exists
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Copy and render static page
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.j2
        mode: '0644'
...
