---
- name: Variables Demo
  hosts: g1
  become: yes
  vars:
    myusername: Nottie

  tasks:
    - name: Update dynamic page
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.html
        mode: '0644'
...
